---
- name: Ensure app dir exists
  file:
    path: /home/cloudcasts/cloudcasts.io
    state: directory
    owner: cloudcasts
    group: cloudcasts

- name: Ensure web root exists
  file:
    path: /home/cloudcasts/cloudcasts.io/public
    state: directory
    owner: cloudcasts
    group: cloudcasts

- name: Add PHP file
  copy:
    src: index.php
    dest: /home/cloudcasts/cloudcasts.io/public/index.php
    owner: cloudcasts
    group: cloudcasts

- name: Remove default Nginx configurations
  command: rm -rf nginx/conf.d/.default.conf && rm -rf nginx/conf.d/no-ssl.default.conf
  args:
    chdir: /etc
  ignore_errors: yes

- name: Add Nginx configuration
  copy:
    src: cloudcasts.io.conf
    dest: /etc/nginx/conf.d/cloudcasts.io.conf
    owner: root
    group: root

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
