galaxy_info:
  role_name: codedeploy-agent
  author: Mark Honomichl
  description: Installs Code Deploy
  company: AustinCloudGuru
  namespace: ausgincloudguru
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Amazon
    versions:
      - all
  - name: Ubuntu
    versions:
      - bionic
      - focal
  - name: EL
    versions:
      - 7
      - 8

  galaxy_tags: 
    - amazon
    - aws
    - codedeploy

dependencies: []
