---
- hosts: all
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - base
    - austincloudguru.codedeploy-agent
    - user
    - php
    - nginx
    - queue
    - app